stages:
  - tests
  - report

tests:
  stage: tests
  services:
    - name: selenium/standalone-chrome:104.0
      alias: chrome
  image: python:3.10.4-slim
  before_script:
    - python3 -m pip install -r requirements.txt --quiet
  script:
    - pytest --alluredir=./allure-results --selenium_host=chrome
  artifacts:
    when: always
    paths:
      - ./allure-results
    expire_in: 1 day
  allow_failure: true


report:
  stage: report
  needs: [ tests ]
  image: frankescobar/allure-docker-service
  script:
    - allure generate -c ./allure-results -o ./allure-report
  artifacts:
    paths:
      - ./allure-report
    expire_in: 1 day